# Generated by Django 5.1.7 on 2025-03-20 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('composition', models.CharField(default='N/A', max_length=255)),
                ('soil_type', models.CharField(default='General', max_length=255)),
                ('crop_name', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_level', models.IntegerField()),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer_app.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(choices=[('Urea', 'Urea'), ('DAP', 'DAP'), ('Potash', 'Potash'), ('NPK', 'NPK')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Online Payment', 'Online Payment'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fertilizer_app.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='SoilCropDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=100)),
                ('crop_name', models.CharField(max_length=100)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer_app.farmer')),
            ],
        ),
    ]
